enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
excluded-patches = "'GmsCore support' 'Spoof video streams'"

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
included-patches = "'Custom branding' 'Change header'"
excluded-patches = "'GmsCore support' 'Spoof video streams'"
